name = "clang-base"

[tools]
cc = "clang"
cxx = "clang++"
ar = "llvm-ar"
asm = "clang"

[flags]
common = []
c = ["-std=c23", "-Wall", "-Wextra", "-Wpedantic"]
cxx = ["-std=gnu++23", "-Wall", "-Wextra", "-Wpedantic"]
asm = []
link = []

[settings]
family = "clang"
debug = false
optimization = "0"
warnings_as_errors = false