name = "gcc-release"
extends = "gcc-base.toml"

[flags]
common_add = ["-O2"]
c_add   = ["-ffunction-sections", "-fdata-sections", "-flto"]
cxx_add = ["-ffunction-sections", "-fdata-sections", "-flto"]

[settings]
debug = false
optimization = "2"

[archive]
strategy = "lto_merged"
exported_symbols_file = "../exports/public_symbols.txt"
filter_exported_symbols = true
preserve_lto_sections = true