name = "gcc-base"

[tools]
cc = "gcc-15"
cxx = "g++-15"
ar = "gcc-ar-15"
asm = "gcc-15"

[flags]
common = []
c = ["-std=c23", "-Wall", "-Wextra", "-Wpedantic"]
cxx = ["-std=gnu++26", "-Wall", "-Wextra", "-Wpedantic"]
asm = []
link = []

[settings]
family = "gcc"
debug = false
optimization = "0"
warnings_as_errors = false
use_modules = true