name = "libcortos"
description = "Optional higher-level RTOS library"

dependencies = ["kernel", "time"]

public_modules = ["cortos", "cortos.sync"]
private_modules = []

source_roots = ["."]
generated_includes = true