name = "port"
kind = "port"
description = "Low-level port layer"

variants = ["boost", "cortex_m"]

dependencies = []

public_modules = []
private_modules = []

source_roots = ["boost"]
generated_includes = true