name = "simulation"
description = "Simulation time driver"

dependencies = ["port"]
public_headers = [
  "time.hpp -> cortos/time.hpp",
  "simulation.hpp -> cortos/time/simulation.hpp",
]
public_modules = []
private_modules = []

source_roots = ["."]
generated_includes = true
