name = "sim"
default_toolchain = "gcc-debug"

[build]
port = "boost"
time_driver = "simulation"
config = "../config_templates/sim.hpp"

[libcortos]
enable = ["sync", "timed_sync"]

[output]
root = "../bld"
archive = "cortos.a"