name = "linux_boost_sim"
default_toolchain = "gcc-debug"

[layout]
project_root = "../"
build_root = "../"
source_root = "../src"
output_root = "../out"

[build]
port = "boost"
time_driver = "simulation"
config_header = "sim.hpp"

[features]
enable = ["sync", "timed_sync"]

[output]
archive = "cortos.a"