name = "sync"
description = "Basic synchronization primitives"

dependencies = ["kernel"]

public_headers = [
  "mutex.hpp -> cyros/sync/mutex.hpp",
]
public_modules = []
private_modules = []

source_roots = ["."]
generated_includes = true
